name: video_mock

models:
  - CogVideoX-5B
  - Wan2.2-T2V-A14B-Diffusers

prompts: prompts/test_video_100.txt
execution_mode: mock

generation_defaults:
  width: 1280
  height: 720
  fps: 16
  num_frames: 81
  guidance_scale: 4.0
  guidance_scale_2: 3.0
  num_inference_steps: 40
